import type { Metadata } from 'next';
import './globals.css';
import { ToastProvider } from '@/hooks/useToasts';
import { ToastsContainer } from '@/components/Toasts';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: 'Social',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='pt-br'>
            <head>
                <link
                    rel='stylesheet'
                    href='http://localhost:5174/shared/App.css'
                />
                <link rel="icon" type="image/svg+xml" href="https://pioneirosdoadvento.com/assets/images/logo.png" />
            </head>

            <body>
                <ToastProvider>
                    <ToastsContainer/>
                    {children}
                </ToastProvider>
            </body>
        </html>
    );
}
